import unittest

from tahoma.protocol import Protocol

SetupInput = {
	"setup": {
		"creationTime": 1433380677011,
		"lastUpdateTime": 1433380677011,
		"id": "SETUP-1234-1234-1234",
		"location": {
			"creationTime": 1433380677011,
			"lastUpdateTime": 1433380677011,
			"addressLine1": "My street",
			"postalCode": "90210",
			"city": "City",
			"country": "Country",
			"timezone": "Europe/City",
			"longitude": 2.313,
			"latitude": 48.237,
			"twilightMode": 2,
			"twilightCity": "city",
			"summerSolsticeDuskMinutes": 1290,
			"winterSolsticeDuskMinutes": 990,
			"twilightOffsetEnabled": False,
			"dawnOffset": 0,
			"duskOffset": 0
		},
		"gateways": [{
			"gatewayId": "1234-4321-1234",
			"type": 15,
			"placeOID": "12345678-1234-1234-1234-123456789001",
			"alive": True,
			"timeReliable": True,
			"connectivity": {
				"status": "OK",
				"protocolVersion": "8"
			},
			"upToDate": True,
			"functions": "INTERNET_AUTHORIZATION,SCENARIO_DOWNLOAD,SCENARIO_AUTO_LAUNCHING,SCENARIO_TELECO_LAUNCHING,INTERNET_UPLOAD,INTERNET_UPDATE,TRIGGERS_SENSORS",
			"mode": "ACTIVE"
		}],
		"devices": [{
			"creationTime": 1433380677011,
			"lastUpdateTime": 1433380677011,
			"label": "Philips Hue Bridge",
			"deviceURL": "hue://1234-1234-1234/123456789012",
			"shortcut": False,
			"controllableName": "hue:BridgeHUEComponent",
			"definition": {
				"states": [{
					"eventBased": False,
					"type": "DataState",
					"qualifiedName": "core:NameState"
				}],
				"widgetName": "HueBridge",
				"uiClass": "ProtocolGateway",
				"qualifiedName": "hue:BridgeHUEComponent",
				"type": "PROTOCOL_GATEWAY"
			},
			"states": [{
				"name": "core:NameState",
				"type": 3,
				"value": "Philips hue"
			}],
			"available": True,
			"enabled": True,
			"placeOID": "12345678-1234-1234-1234-123456789002",
			"type": 5,
			"widget": "HueBridge",
			"oid": "12345678-1234-1234-1234-12345678900a",
			"uiClass": "ProtocolGateway"
		}, {
			"creationTime": 1433380677011,
			"lastUpdateTime": 1433380677011,
			"label": "Light name",
			"deviceURL": "hue://1234-1234-1234/123456789012/lights/1",
			"shortcut": False,
			"controllableName": "hue:BloomHUEComponent",
			"definition": {
				"commands": [{
					"commandName": "identify",
					"nparams": 0,
					"qualifiedName": "core:IdentificationCommand"
				}, {
					"commandName": "off",
					"nparams": 0,
					"qualifiedName": "core:OffCommand"
				}, {
					"commandName": "on",
					"nparams": 0,
					"qualifiedName": "core:OnCommand"
				}, {
					"commandName": "onWithTimer",
					"nparams": 1,
					"qualifiedName": "core:OnWithTimerCommand"
				}, {
					"commandName": "refreshState",
					"nparams": 0,
					"qualifiedName": "core:RefreshStateCommand"
				}, {
					"commandName": "setCieColorSpaceXY",
					"nparams": 2,
					"qualifiedName": "core:SetCieColorSpaceXYCommand"
				}, {
					"commandName": "setHSB",
					"nparams": 3,
					"qualifiedName": "core:SetHSBColorCommand"
				}, {
					"commandName": "setHueAndSaturation",
					"nparams": 2,
					"qualifiedName": "core:SetHueAndSaturationCommand"
				}, {
					"commandName": "setIntensity",
					"nparams": 1,
					"qualifiedName": "core:SetIntensityCommand"
				}, {
					"commandName": "setIntensityWithTimer",
					"nparams": 3,
					"qualifiedName": "core:SetIntensityWithTimerCommand"
				}, {
					"commandName": "setName",
					"nparams": 1,
					"qualifiedName": "core:SetNameCommand"
				}, {
					"commandName": "setOnOff",
					"nparams": 1,
					"qualifiedName": "core:SetOnOffCommand"
				}, {
					"commandName": "setRGB",
					"nparams": 3,
					"qualifiedName": "core:SetRGBColorCommand"
				}, {
					"commandName": "setXYB",
					"nparams": 3,
					"qualifiedName": "core:SetXYBColorCommand"
				}],
				"states": [{
					"eventBased": False,
					"type": "ContinuousState",
					"qualifiedName": "core:CieColorSpaceXState"
				}, {
					"eventBased": False,
					"type": "ContinuousState",
					"qualifiedName": "core:CieColorSpaceYState"
				}, {
					"eventBased": False,
					"type": "ContinuousState",
					"qualifiedName": "core:ColorHueState"
				}, {
					"eventBased": False,
					"type": "ContinuousState",
					"qualifiedName": "core:ColorSaturationState"
				}, {
					"eventBased": False,
					"type": "ContinuousState",
					"qualifiedName": "core:LightIntensityState"
				}, {
					"eventBased": False,
					"type": "DataState",
					"qualifiedName": "core:NameState"
				}, {
					"eventBased": False,
					"values": ["off", "on"],
					"type": "DiscreteState",
					"qualifiedName": "core:OnOffState"
				}, {
					"eventBased": False,
					"values": ["ct", "hs", "xy"],
					"type": "DiscreteState",
					"qualifiedName": "hue:HueColorModeState"
				}],
				"dataProperties": [{
					"value": "3000",
					"qualifiedName": "core:identifyInterval"
				}],
				"widgetName": "DimmerHueSaturationLight",
				"uiClass": "Light",
				"qualifiedName": "hue:BloomHUEComponent",
				"type": "ACTUATOR"
			},
			"states": [{
				"name": "core:ColorHueState",
				"type": 1,
				"value": 265
			}, {
				"name": "core:ColorSaturationState",
				"type": 1,
				"value": 44
			}, {
				"name": "core:CieColorSpaceXState",
				"type": 2,
				"value": 0.3505
			}, {
				"name": "core:CieColorSpaceYState",
				"type": 2,
				"value": 0.2792
			}, {
				"name": "hue:HueColorModeState",
				"type": 3,
				"value": "hs"
			}, {
				"name": "core:NameState",
				"type": 3,
				"value": "Light name"
			}, {
				"name": "core:OnOffState",
				"type": 3,
				"value": "off"
			}, {
				"name": "core:LightIntensityState",
				"type": 1,
				"value": 0
			}],
			"attributes": [{
				"name": "core:LampType",
				"type": 3,
				"value": "bloom"
			}],
			"available": True,
			"enabled": True,
			"placeOID": "12345678-1234-1234-1234-123456789003",
			"type": 1,
			"widget": "DimmerHueSaturationLight",
			"oid": "12345678-1234-1234-1234-12345678900b",
			"uiClass": "Light"
		}, {
			"creationTime": 1433380677011,
			"lastUpdateTime": 1433380677011,
			"label": "shutt1",
			"deviceURL": "io://1234-1234-1234/12345611",
			"shortcut": False,
			"controllableName": "io:RollerShutterVeluxIOComponent",
			"definition": {
				"commands": [{
					"commandName": "close",
					"nparams": 0,
					"qualifiedName": "core:CloseCommand"
				}, {
					"commandName": "delayedStopIdentify",
					"nparams": 1,
					"qualifiedName": "core:DelayedStopIdentificationCommand"
				}, {
					"commandName": "down",
					"nparams": 0,
					"qualifiedName": "core:DownCommand"
				}, {
					"commandName": "getName",
					"nparams": 0,
					"qualifiedName": "core:GetNameCommand"
				}, {
					"commandName": "identify",
					"nparams": 0,
					"qualifiedName": "core:IdentificationCommand"
				}, {
					"commandName": "my",
					"nparams": 0,
					"qualifiedName": "core:MyCommand"
				}, {
					"commandName": "open",
					"nparams": 0,
					"qualifiedName": "core:OpenCommand"
				}, {
					"commandName": "setClosure",
					"nparams": 1,
					"qualifiedName": "core:SetClosureCommand"
				}, {
					"commandName": "setDeployment",
					"nparams": 1,
					"qualifiedName": "core:SetDeploymentCommand"
				}, {
					"commandName": "setName",
					"nparams": 1,
					"qualifiedName": "core:SetNameCommand"
				}, {
					"commandName": "setPosition",
					"nparams": 1,
					"qualifiedName": "core:SetPositionCommand"
				}, {
					"commandName": "setSecuredPosition",
					"nparams": 1,
					"qualifiedName": "core:SetSecuredPositionCommand"
				}, {
					"commandName": "startIdentify",
					"nparams": 0,
					"qualifiedName": "core:StartIdentificationCommand"
				}, {
					"commandName": "stopIdentify",
					"nparams": 0,
					"qualifiedName": "core:StopIdentificationCommand"
				}, {
					"commandName": "up",
					"nparams": 0,
					"qualifiedName": "core:UpCommand"
				}, {
					"commandName": "wink",
					"nparams": 1,
					"qualifiedName": "core:WinkCommand"
				}, {
					"commandName": "setMemorized1Position",
					"nparams": 1,
					"qualifiedName": "io:SetMemorized1PositionCommand"
				}],
				"states": [{
					"eventBased": False,
					"type": "ContinuousState",
					"qualifiedName": "core:ClosureState"
				}, {
					"eventBased": False,
					"type": "ContinuousState",
					"qualifiedName": "core:Memorized1PositionState"
				}, {
					"eventBased": False,
					"type": "DataState",
					"qualifiedName": "core:NameState"
				}, {
					"eventBased": False,
					"values": ["closed", "open"],
					"type": "DiscreteState",
					"qualifiedName": "core:OpenClosedState"
				}, {
					"eventBased": False,
					"type": "ContinuousState",
					"qualifiedName": "core:PriorityLockTimerState"
				}, {
					"eventBased": False,
					"type": "ContinuousState",
					"qualifiedName": "core:SecuredPositionState"
				}, {
					"eventBased": False,
					"values": ["LSC", "SAAC", "SFC", "UPS", "externalGateway", "localUser", "myself", "rain", "security", "timer", "user", "wind"],
					"type": "DiscreteState",
					"qualifiedName": "io:PriorityLockOriginatorState"
				}],
				"dataProperties": [{
					"value": "500",
					"qualifiedName": "core:identifyInterval"
				}],
				"widgetName": "PositionableTiltedRollerShutter",
				"uiClass": "RollerShutter",
				"qualifiedName": "io:RollerShutterVeluxIOComponent",
				"type": "ACTUATOR"
			},
			"states": [{
				"name": "core:NameState",
				"type": 3,
				"value": "shutt1"
			}, {
				"name": "core:PriorityLockTimerState",
				"type": 1,
				"value": 0
			}, {
				"name": "core:ClosureState",
				"type": 1,
				"value": 0
			}, {
				"name": "core:OpenClosedState",
				"type": 3,
				"value": "open"
			}],
			"available": True,
			"enabled": True,
			"placeOID": "12345678-1234-1234-1234-123456789004",
			"type": 1,
			"widget": "PositionableTiltedRollerShutter",
			"oid": "12345678-1234-1234-1234-12345678900c",
			"uiClass": "RollerShutter"
		}, {
			"creationTime": 1433380677011,
			"lastUpdateTime": 1433380677011,
			"label": "shutt2",
			"deviceURL": "io://1234-1234-1234/12345622",
			"shortcut": False,
			"controllableName": "io:RollerShutterVeluxIOComponent",
			"definition": {
				"commands": [{
					"commandName": "close",
					"nparams": 0,
					"qualifiedName": "core:CloseCommand"
				}, {
					"commandName": "delayedStopIdentify",
					"nparams": 1,
					"qualifiedName": "core:DelayedStopIdentificationCommand"
				}, {
					"commandName": "down",
					"nparams": 0,
					"qualifiedName": "core:DownCommand"
				}, {
					"commandName": "getName",
					"nparams": 0,
					"qualifiedName": "core:GetNameCommand"
				}, {
					"commandName": "identify",
					"nparams": 0,
					"qualifiedName": "core:IdentificationCommand"
				}, {
					"commandName": "my",
					"nparams": 0,
					"qualifiedName": "core:MyCommand"
				}, {
					"commandName": "open",
					"nparams": 0,
					"qualifiedName": "core:OpenCommand"
				}, {
					"commandName": "setClosure",
					"nparams": 1,
					"qualifiedName": "core:SetClosureCommand"
				}, {
					"commandName": "setDeployment",
					"nparams": 1,
					"qualifiedName": "core:SetDeploymentCommand"
				}, {
					"commandName": "setName",
					"nparams": 1,
					"qualifiedName": "core:SetNameCommand"
				}, {
					"commandName": "setPosition",
					"nparams": 1,
					"qualifiedName": "core:SetPositionCommand"
				}, {
					"commandName": "setSecuredPosition",
					"nparams": 1,
					"qualifiedName": "core:SetSecuredPositionCommand"
				}, {
					"commandName": "startIdentify",
					"nparams": 0,
					"qualifiedName": "core:StartIdentificationCommand"
				}, {
					"commandName": "stopIdentify",
					"nparams": 0,
					"qualifiedName": "core:StopIdentificationCommand"
				}, {
					"commandName": "up",
					"nparams": 0,
					"qualifiedName": "core:UpCommand"
				}, {
					"commandName": "wink",
					"nparams": 1,
					"qualifiedName": "core:WinkCommand"
				}, {
					"commandName": "setMemorized1Position",
					"nparams": 1,
					"qualifiedName": "io:SetMemorized1PositionCommand"
				}],
				"states": [{
					"eventBased": False,
					"type": "ContinuousState",
					"qualifiedName": "core:ClosureState"
				}, {
					"eventBased": False,
					"type": "ContinuousState",
					"qualifiedName": "core:Memorized1PositionState"
				}, {
					"eventBased": False,
					"type": "DataState",
					"qualifiedName": "core:NameState"
				}, {
					"eventBased": False,
					"values": ["closed", "open"],
					"type": "DiscreteState",
					"qualifiedName": "core:OpenClosedState"
				}, {
					"eventBased": False,
					"type": "ContinuousState",
					"qualifiedName": "core:PriorityLockTimerState"
				}, {
					"eventBased": False,
					"type": "ContinuousState",
					"qualifiedName": "core:SecuredPositionState"
				}, {
					"eventBased": False,
					"values": ["LSC", "SAAC", "SFC", "UPS", "externalGateway", "localUser", "myself", "rain", "security", "timer", "user", "wind"],
					"type": "DiscreteState",
					"qualifiedName": "io:PriorityLockOriginatorState"
				}],
				"dataProperties": [{
					"value": "500",
					"qualifiedName": "core:identifyInterval"
				}],
				"widgetName": "PositionableTiltedRollerShutter",
				"uiClass": "RollerShutter",
				"qualifiedName": "io:RollerShutterVeluxIOComponent",
				"type": "ACTUATOR"
			},
			"states": [{
				"name": "core:NameState",
				"type": 3,
				"value": "shutt2"
			}, {
				"name": "core:PriorityLockTimerState",
				"type": 1,
				"value": 0
			}, {
				"name": "core:ClosureState",
				"type": 1,
				"value": 0
			}, {
				"name": "core:OpenClosedState",
				"type": 3,
				"value": "open"
			}],
			"available": True,
			"enabled": True,
			"placeOID": "12345678-1234-1234-1234-123456789005",
			"type": 1,
			"widget": "PositionableTiltedRollerShutter",
			"oid": "12345678-1234-1234-1234-12345678900d",
			"uiClass": "RollerShutter"
		}, {
			"creationTime": 1433380677011,
			"lastUpdateTime": 1433380677011,
			"label": "window1",
			"deviceURL": "io://1234-1234-1234/12345633",
			"shortcut": False,
			"controllableName": "io:WindowOpenerVeluxIOComponent",
			"definition": {
				"commands": [{
					"commandName": "close",
					"nparams": 0,
					"qualifiedName": "core:CloseCommand"
				}, {
					"commandName": "delayedStopIdentify",
					"nparams": 1,
					"qualifiedName": "core:DelayedStopIdentificationCommand"
				}, {
					"commandName": "getName",
					"nparams": 0,
					"qualifiedName": "core:GetNameCommand"
				}, {
					"commandName": "identify",
					"nparams": 0,
					"qualifiedName": "core:IdentificationCommand"
				}, {
					"commandName": "open",
					"nparams": 0,
					"qualifiedName": "core:OpenCommand"
				}, {
					"commandName": "setClosure",
					"nparams": 1,
					"qualifiedName": "core:SetClosureCommand"
				}, {
					"commandName": "setName",
					"nparams": 1,
					"qualifiedName": "core:SetNameCommand"
				}, {
					"commandName": "startIdentify",
					"nparams": 0,
					"qualifiedName": "core:StartIdentificationCommand"
				}, {
					"commandName": "stopIdentify",
					"nparams": 0,
					"qualifiedName": "core:StopIdentificationCommand"
				}, {
					"commandName": "wink",
					"nparams": 1,
					"qualifiedName": "core:WinkCommand"
				}],
				"states": [{
					"eventBased": False,
					"type": "ContinuousState",
					"qualifiedName": "core:ClosureState"
				}, {
					"eventBased": False,
					"type": "DataState",
					"qualifiedName": "core:NameState"
				}, {
					"eventBased": False,
					"values": ["closed", "open"],
					"type": "DiscreteState",
					"qualifiedName": "core:OpenClosedState"
				}, {
					"eventBased": False,
					"type": "ContinuousState",
					"qualifiedName": "core:PriorityLockTimerState"
				}, {
					"eventBased": False,
					"values": ["LSC", "SAAC", "SFC", "UPS", "externalGateway", "localUser", "myself", "rain", "security", "timer", "user", "wind"],
					"type": "DiscreteState",
					"qualifiedName": "io:PriorityLockOriginatorState"
				}],
				"dataProperties": [{
					"value": "500",
					"qualifiedName": "core:identifyInterval"
				}],
				"widgetName": "PositionableTiltedWindow",
				"uiClass": "Window",
				"qualifiedName": "io:WindowOpenerVeluxIOComponent",
				"type": "ACTUATOR"
			},
			"states": [{
				"name": "core:NameState",
				"type": 3,
				"value": "window1"
			}, {
				"name": "core:PriorityLockTimerState",
				"type": 1,
				"value": 0
			}, {
				"name": "core:ClosureState",
				"type": 1,
				"value": 100
			}, {
				"name": "core:OpenClosedState",
				"type": 3,
				"value": "closed"
			}],
			"available": True,
			"enabled": True,
			"placeOID": "12345678-1234-1234-1234-123456789006",
			"type": 1,
			"widget": "PositionableTiltedWindow",
			"oid": "12345678-1234-1234-1234-12345678900e",
			"uiClass": "Window"
		}, {
			"creationTime": 1433380677011,
			"lastUpdateTime": 1433380677011,
			"label": "window2",
			"deviceURL": "io://1234-1234-1234/12345644",
			"shortcut": False,
			"controllableName": "io:WindowOpenerVeluxIOComponent",
			"definition": {
				"commands": [{
					"commandName": "close",
					"nparams": 0,
					"qualifiedName": "core:CloseCommand"
				}, {
					"commandName": "delayedStopIdentify",
					"nparams": 1,
					"qualifiedName": "core:DelayedStopIdentificationCommand"
				}, {
					"commandName": "getName",
					"nparams": 0,
					"qualifiedName": "core:GetNameCommand"
				}, {
					"commandName": "identify",
					"nparams": 0,
					"qualifiedName": "core:IdentificationCommand"
				}, {
					"commandName": "open",
					"nparams": 0,
					"qualifiedName": "core:OpenCommand"
				}, {
					"commandName": "setClosure",
					"nparams": 1,
					"qualifiedName": "core:SetClosureCommand"
				}, {
					"commandName": "setName",
					"nparams": 1,
					"qualifiedName": "core:SetNameCommand"
				}, {
					"commandName": "startIdentify",
					"nparams": 0,
					"qualifiedName": "core:StartIdentificationCommand"
				}, {
					"commandName": "stopIdentify",
					"nparams": 0,
					"qualifiedName": "core:StopIdentificationCommand"
				}, {
					"commandName": "wink",
					"nparams": 1,
					"qualifiedName": "core:WinkCommand"
				}],
				"states": [{
					"eventBased": False,
					"type": "ContinuousState",
					"qualifiedName": "core:ClosureState"
				}, {
					"eventBased": False,
					"type": "DataState",
					"qualifiedName": "core:NameState"
				}, {
					"eventBased": False,
					"values": ["closed", "open"],
					"type": "DiscreteState",
					"qualifiedName": "core:OpenClosedState"
				}, {
					"eventBased": False,
					"type": "ContinuousState",
					"qualifiedName": "core:PriorityLockTimerState"
				}, {
					"eventBased": False,
					"values": ["LSC", "SAAC", "SFC", "UPS", "externalGateway", "localUser", "myself", "rain", "security", "timer", "user", "wind"],
					"type": "DiscreteState",
					"qualifiedName": "io:PriorityLockOriginatorState"
				}],
				"dataProperties": [{
					"value": "500",
					"qualifiedName": "core:identifyInterval"
				}],
				"widgetName": "PositionableTiltedWindow",
				"uiClass": "Window",
				"qualifiedName": "io:WindowOpenerVeluxIOComponent",
				"type": "ACTUATOR"
			},
			"states": [{
				"name": "core:NameState",
				"type": 3,
				"value": "window2"
			}, {
				"name": "core:PriorityLockTimerState",
				"type": 1,
				"value": 0
			}, {
				"name": "core:ClosureState",
				"type": 1,
				"value": 100
			}, {
				"name": "core:OpenClosedState",
				"type": 3,
				"value": "closed"
			}],
			"available": True,
			"enabled": True,
			"placeOID": "12345678-1234-1234-1234-123456789007",
			"type": 1,
			"widget": "PositionableTiltedWindow",
			"oid": "12345678-1234-1234-1234-12345678900f",
			"uiClass": "Window"
		}],
		"resellerDelegationType": "NEVER",
		"rootPlace": {
			"creationTime": 1433380677011,
			"lastUpdateTime": 1433380677011,
			"label": "House",
			"type": 200,
			"oid": "12345678-1234-1234-1234-1234567890aa",
			"subPlaces": [{
				"creationTime": 1433380677011,
				"lastUpdateTime": 1433380677011,
				"label": "1. Floor",
				"type": 104,
				"oid": "12345678-1234-1234-1234-1234567890bb",
				"subPlaces": [{
					"creationTime": 1433380677011,
					"lastUpdateTime": 1433380677011,
					"label": "Kitchen",
					"type": 11,
					"metadata": "{\"tahoma\":{\"order\":1}}",
					"oid": "12345678-1234-1234-1234-1234567890cc"
				}, {
					"creationTime": 1433380677011,
					"lastUpdateTime": 1433380677011,
					"label": "Room",
					"type": 6,
					"metadata": "{\"tahoma\":{\"order\":2}}",
					"oid": "12345678-1234-1234-1234-1234567890dd"
				}]
			}, {
				"creationTime": 1433380677011,
				"lastUpdateTime": 1433380677011,
				"label": "2. Floor",
				"type": 110,
				"oid": "12345678-1234-1234-1234-1234567890ee",
				"subPlaces": [{
					"creationTime": 1433380677011,
					"lastUpdateTime": 1433380677011,
					"label": "Above room",
					"type": 27,
					"metadata": "{\"tahoma\":{\"order\":3}}",
					"oid": "12345678-1234-1234-1234-1234567890ff"
				}]
			}]
		},
		"features": [{
			"name": "tahoma-premium",
			"source": "GATEWAY_TYPE"
		}],
		"place": {
			"type": 200,
			"creationTime": 1433380677011,
			"oid": "12345678-1234-1234-1234-1234567890aa",
			"label": "House",
			"lastUpdateTime": 1433380677011,
			"place": [{
				"type": 104,
				"creationTime": 1433380677011,
				"oid": "12345678-1234-1234-1234-1234567890bb",
				"label": "1. Floor",
				"lastUpdateTime": 1433380677011,
				"place": [{
					"type": 11,
					"creationTime": 1433380677011,
					"oid": "12345678-1234-1234-1234-1234567890cc",
					"label": "Kitchen",
					"lastUpdateTime": 1433380677011
				}, {
					"type": 6,
					"creationTime": 1433380677011,
					"oid": "12345678-1234-1234-1234-1234567890dd",
					"label": "Room",
					"lastUpdateTime": 1433380677011
				}]
			}, {
				"type": 110,
				"creationTime": 1433380677011,
				"oid": "12345678-1234-1234-1234-1234567890ee",
				"label": "2. Floor",
				"lastUpdateTime": 1433380677011,
				"place": [{
					"type": 27,
					"creationTime": 1433380677011,
					"oid": "12345678-1234-1234-1234-1234567890ff",
					"label": "Above room",
					"lastUpdateTime": 1433380677011
				}]
			}]
		}
	}
}


class TestProtocolGetSetup(unittest.TestCase):

    def test_parse(self):
        tahoma = Protocol("", "", unittest=1 )
        tahoma._getSetup(SetupInput) # only for unit tests

        self.assertEqual(tahoma.location["postalCode"], "90210")
        self.assertTrue(tahoma.gateway[0]["alive"])
        self.assertEqual(tahoma.gateway[0]["connectivity"]["protocolVersion"], "8")
        self.assertEqual(len(tahoma.getDevices()), 6)
        device = tahoma.getDevice("hue://1234-1234-1234/123456789012/lights/1")
        self.assertEqual(device.activeStates["core:CieColorSpaceYState"], 0.2792)


